sonar.organization=shacharm2
sonar.projectKey=shacharm2_worthless
sonar.projectName=worthless
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
