"""Phase 2.c — ``integration.apply_unlock()`` unit + functional tests.

Spec: ``engineering/research/openclaw-WOR-431-phase-2-spec.md`` §"Phase 2.c —
``unlock`` integration", §"Failure modes" rows RT-01/02/03 + F-XS-40/41,
§"Locked decisions" L1, L2, L3.

``apply_unlock`` is the symmetric undo of Phase 2.b's ``apply_lock``. It
runs from ``worthless unlock`` after the ``.env``/DB are restored. Per
L1/L2: failures here NEVER cause unlock-core to fail.

Each test docstring opens with ``"<F-ID/scope>: <description>"`` so the
coverage matrix can be regenerated by grep.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Fixtures: ``fake_home`` + ``openclaw_present`` provided by conftest.py.
# ---------------------------------------------------------------------------


def _seed_provider(config_path: Path, name: str, base_url: str, api_key: str = "shard-a") -> None:
    """Helper: write a single provider entry into openclaw.json."""
    data = json.loads(config_path.read_text(encoding="utf-8"))
    data.setdefault("models", {}).setdefault("providers", {})[name] = {
        "baseUrl": base_url,
        "apiKey": api_key,
    }
    config_path.write_text(
        json.dumps(data, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Public API surface — sanity
# ---------------------------------------------------------------------------


def test_apply_unlock_is_exported() -> None:
    """Phase 2.c spec: ``integration.apply_unlock`` must be importable as the
    public symmetric-undo Stage-3 entry point.
    """
    from worthless.openclaw import integration

    assert hasattr(integration, "apply_unlock"), "apply_unlock missing"


# ---------------------------------------------------------------------------
# Detection short-circuit — no OpenClaw on host
# ---------------------------------------------------------------------------


def test_apply_unlock_no_openclaw_returns_early(fake_home: Path) -> None:
    """L1/L2 + Phase 2.c: host without OpenClaw → result with detected=False,
    no I/O, no exceptions. Symmetric with apply_lock's early exit.
    """
    from worthless.openclaw import integration

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    assert result.detected is False
    assert result.providers_set == ()
    assert result.skill_installed is False
    assert result.events == ()
    # No accidental file creation.
    assert not (fake_home / ".openclaw").exists()


# ---------------------------------------------------------------------------
# Provider removal
# ---------------------------------------------------------------------------


def test_apply_unlock_removes_provider_entry(openclaw_present: dict[str, Path]) -> None:
    """Phase 2.c: pre-stage ``worthless-openai`` in openclaw.json → after
    apply_unlock, that entry is gone (symmetric undo of Phase 2.b set_provider).
    """
    from worthless.openclaw import integration

    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]
    assert "worthless-openai" not in providers, providers
    assert result.detected is True


def test_apply_unlock_skips_non_worthless_entries(openclaw_present: dict[str, Path]) -> None:
    """L3 + Phase 2.c: pre-stage non-worthless ``openai`` entry → after
    apply_unlock, that entry is preserved. We only own ``worthless-*``.
    """
    from worthless.openclaw import integration

    _seed_provider(
        openclaw_present["config_path"],
        "openai",
        "https://api.openai.com",
        api_key="real-user-key",
    )
    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]
    assert "openai" in providers, "user's manual entry must survive"
    assert providers["openai"]["apiKey"] == "real-user-key"
    assert "worthless-openai" not in providers


# ---------------------------------------------------------------------------
# Skill folder removal
# ---------------------------------------------------------------------------


def test_apply_unlock_removes_skill_folder(openclaw_present: dict[str, Path]) -> None:
    """Phase 2.c + L3: pre-stage skill folder under workspace → after
    apply_unlock, folder is gone (symmetric undo of skill.install).
    """
    from worthless.openclaw import integration

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("placeholder\n", encoding="utf-8")

    integration.apply_unlock(aliases=[])

    assert not skill_dir.exists()


def test_apply_unlock_with_remove_skill_false_keeps_skill(
    openclaw_present: dict[str, Path],
) -> None:
    """Phase 2.c: ``remove_skill=False`` → provider entries are removed but
    skill folder is preserved. Lets future doctor --fix tear down only one
    half independently if desired.
    """
    from worthless.openclaw import integration

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("placeholder\n", encoding="utf-8")
    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    integration.apply_unlock(
        aliases=[("openai", "openai-deadbeef")],
        remove_skill=False,
    )

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    assert "worthless-openai" not in data["models"]["providers"]
    assert skill_dir.exists(), "skill folder must survive remove_skill=False"
    assert (skill_dir / "SKILL.md").exists()


# ---------------------------------------------------------------------------
# Idempotency — running twice on the same input is a no-op the second time
# ---------------------------------------------------------------------------


def test_apply_unlock_idempotent(openclaw_present: dict[str, Path]) -> None:
    """IDEM (Phase 2.c): apply_unlock twice on the same input → second call
    is a no-op (no errors, no provider removed because it's already gone).
    """
    from worthless.openclaw import integration

    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    first = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])
    second = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    # Both calls succeed; second has no error events.
    error_events = [e for e in second.events if e.level == "error"]
    assert error_events == [], error_events
    # And both report detected=True (OpenClaw is still on the host).
    assert first.detected is True
    assert second.detected is True


# ---------------------------------------------------------------------------
# Partial-failure paths (L1: NEVER raise into unlock-core)
# ---------------------------------------------------------------------------


def test_apply_unlock_partial_failure_returns_result(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-40 analogue: monkeypatch unset_provider to raise OSError
    → result reflects partial failure with a structured event, no raise.
    """
    from worthless.openclaw import config as config_mod
    from worthless.openclaw import integration

    def _exploding_unset(*_: object, **__: object) -> None:
        raise OSError("simulated EACCES on openclaw.json")

    monkeypatch.setattr(config_mod, "unset_provider", _exploding_unset)

    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    # Must not raise.
    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    assert result.detected is True
    error_events = [e for e in result.events if e.level == "error"]
    assert error_events, "OSError must surface as a structured event, not a raise"


def test_apply_unlock_partial_failure_config_unreadable(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-40 (CONFIG_UNREADABLE branch): monkeypatch unset_provider
    to raise OpenclawConfigError → result has CONFIG_UNREADABLE event,
    skipped provider list populated, no raise into unlock-core.
    """
    from worthless.openclaw import config as config_mod
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    def _raise_cfg(*_: object, **__: object) -> None:
        raise config_mod.OpenclawConfigError("simulated malformed JSON")

    monkeypatch.setattr(config_mod, "unset_provider", _raise_cfg)

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    codes = [e.code for e in result.events]
    assert OpenclawErrorCode.CONFIG_UNREADABLE in codes, codes
    assert ("worthless-openai", "config_unreadable") in result.providers_skipped


def test_apply_unlock_skill_uninstall_oserror_returns_result(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-41 (OSError branch): skill.uninstall raises a raw OSError
    (not OpenclawIntegrationError) → apply_unlock surfaces it as a
    SKILL_INSTALL_FAILED event without re-raising.
    """
    from worthless.openclaw import integration
    from worthless.openclaw import skill as skill_mod
    from worthless.openclaw.errors import OpenclawErrorCode

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)

    def _raise_oserror(*_: object, **__: object) -> None:
        raise OSError("simulated EACCES on rmtree")

    monkeypatch.setattr(skill_mod, "uninstall", _raise_oserror)

    result = integration.apply_unlock(aliases=[])

    codes = [e.code for e in result.events]
    assert OpenclawErrorCode.SKILL_INSTALL_FAILED in codes, codes


def test_apply_unlock_skill_uninstall_failure_returns_result(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-41 analogue: skill.uninstall raises → apply_unlock
    surfaces it as a structured event, never re-raises. Provider entry
    cleanup must still complete.
    """
    from worthless.openclaw import integration
    from worthless.openclaw import skill as skill_mod
    from worthless.openclaw.errors import (
        OpenclawErrorCode,
        OpenclawIntegrationError,
    )

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("placeholder\n", encoding="utf-8")
    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    def _exploding_uninstall(*_: object, **__: object) -> None:
        raise OpenclawIntegrationError(
            OpenclawErrorCode.SKILL_INSTALL_FAILED,
            "simulated uninstall failure",
        )

    monkeypatch.setattr(skill_mod, "uninstall", _exploding_uninstall)

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    error_events = [e for e in result.events if e.level == "error"]
    assert error_events, "skill failure must surface as a structured event"
    # Provider half still completed.
    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    assert "worthless-openai" not in data["models"]["providers"]


# ---------------------------------------------------------------------------
# RT-01: round-trip apply_lock → apply_unlock = byte-identical pre-lock state
# ---------------------------------------------------------------------------


def test_apply_lock_then_apply_unlock_round_trip_byte_identical(
    openclaw_present: dict[str, Path],
) -> None:
    """RT-01 (Phase 2.c spec): apply_lock followed by apply_unlock leaves
    openclaw.json byte-identical to its pre-apply_lock state. Phase 1's
    sort_keys=True atomic write makes byte-comparison deterministic.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    pre_bytes = config_path.read_bytes()

    integration.apply_lock(planned_updates=[("openai", "openai-deadbeef", "shard-a-token")])
    # Sanity: lock did write the entry.
    mid = json.loads(config_path.read_text(encoding="utf-8"))
    assert "worthless-openai" in mid["models"]["providers"]

    integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    post_bytes = config_path.read_bytes()
    assert post_bytes == pre_bytes, (
        "RT-01 violated: openclaw.json differs after lock→unlock round-trip"
    )
    # And the skill folder we installed during apply_lock got swept too.
    assert not (openclaw_present["workspace"] / "skills" / "worthless").exists()


# ---------------------------------------------------------------------------
# RT-02: multi-alias isolation — unlock A leaves B's worthless-* entries intact
# ---------------------------------------------------------------------------


def test_apply_unlock_leaves_other_worthless_entries_intact(
    openclaw_present: dict[str, Path],
) -> None:
    """RT-02 (Phase 2.c spec): lock A → lock B → unlock A; B's worthless-*
    entry must survive. Each ``apply_unlock`` call removes ONLY the providers
    named in ``aliases`` — never sweeps other ``worthless-*`` entries that
    represent still-locked aliases under a different provider.

    This is the multi-tenant isolation guarantee: a user with both an
    OpenAI key and an Anthropic key can ``unlock`` one without losing the
    other's OpenClaw routing.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    # Simulate state after lock A (openai) + lock B (anthropic).
    _seed_provider(
        config_path,
        "worthless-openai",
        "http://127.0.0.1:8787/openai-aaaa1111/v1",
    )
    _seed_provider(
        config_path,
        "worthless-anthropic",
        "http://127.0.0.1:8787/anthropic-bbbb2222/v1",
    )

    # Unlock ONLY the openai alias.
    result = integration.apply_unlock(
        aliases=[("openai", "openai-aaaa1111")],
        # Don't sweep the skill folder — anthropic alias still needs it.
        remove_skill=False,
    )

    providers = json.loads(config_path.read_text(encoding="utf-8"))["models"]["providers"]
    assert "worthless-openai" not in providers
    assert "worthless-anthropic" in providers, (
        f"RT-02 violated: anthropic entry got swept during openai unlock: {providers}"
    )
    assert providers["worthless-anthropic"]["baseUrl"] == (
        "http://127.0.0.1:8787/anthropic-bbbb2222/v1"
    ), "RT-02 violated: anthropic baseUrl mutated"
    assert "worthless-openai" in result.providers_set
    # Anthropic is NOT mentioned in providers_set OR providers_skipped — it
    # wasn't in the unlock request.
    assert all("anthropic" not in name for name in result.providers_set)
    assert all("anthropic" not in name for name, _reason in result.providers_skipped)


def test_apply_unlock_leaves_non_worthless_providers_intact(
    openclaw_present: dict[str, Path],
) -> None:
    """RT-02 sibling: a user-managed provider (e.g. raw ``openai`` without
    the ``worthless-`` prefix) must NEVER be touched. Phase 1
    ``unset_provider`` is keyed by exact name — this test pins the
    contract end-to-end through ``apply_unlock``.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    _seed_provider(
        config_path,
        "worthless-openai",
        "http://127.0.0.1:8787/openai-aaaa1111/v1",
    )
    # User's manual provider — different name, different baseUrl.
    _seed_provider(
        config_path,
        "openai",
        "https://api.openai.com/v1",
        api_key="sk-user-managed",
    )

    integration.apply_unlock(aliases=[("openai", "openai-aaaa1111")])

    providers = json.loads(config_path.read_text(encoding="utf-8"))["models"]["providers"]
    assert "worthless-openai" not in providers
    assert "openai" in providers, "user-managed 'openai' provider got swept"
    assert providers["openai"]["baseUrl"] == "https://api.openai.com/v1"


# ---------------------------------------------------------------------------
# RT-03 / CONFIG_MISSING: openclaw.json deleted between lock and unlock
# ---------------------------------------------------------------------------


def test_apply_unlock_emits_config_missing_when_config_deleted(
    openclaw_present: dict[str, Path],
) -> None:
    """RT-03 (Phase 2.c spec): user manually deletes openclaw.json between
    ``lock`` and ``unlock`` (or some other tool removed it). detect()'s
    presence verdict is OR(config, workspace) — workspace alive keeps us in
    the present=True path. apply_unlock must surface
    ``OpenclawErrorCode.CONFIG_MISSING`` instead of silently no-opping, so
    doctor / --json can report the user-visible state. Stage B (skill
    removal) still runs.
    """
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    # Pre-install the skill so we can verify Stage B still runs.
    skill_root = openclaw_present["workspace"] / "skills" / "worthless"
    skill_root.mkdir(parents=True)
    (skill_root / "SKILL.md").write_text("placeholder", encoding="utf-8")

    # Delete config — workspace stays.
    openclaw_present["config_path"].unlink()

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    assert result.detected is True
    codes = [event.code for event in result.events]
    assert OpenclawErrorCode.CONFIG_MISSING in codes, codes
    # All requested providers reported as skipped with the named reason.
    assert ("worthless-openai", "config_missing") in result.providers_skipped
    assert result.providers_set == ()
    # Stage B (skill removal) still ran.
    assert not skill_root.exists()


def test_apply_unlock_config_missing_emits_one_event_for_many_aliases(
    openclaw_present: dict[str, Path],
) -> None:
    """CONFIG_MISSING is per-config, not per-alias — one event no matter
    how many aliases the caller passed. Each alias still gets its own
    ``providers_skipped`` row so --json downstream can render them.
    """
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    openclaw_present["config_path"].unlink()

    result = integration.apply_unlock(
        aliases=[
            ("openai", "openai-aaaa1111"),
            ("anthropic", "anthropic-bbbb2222"),
        ]
    )

    config_missing_events = [
        event for event in result.events if event.code == OpenclawErrorCode.CONFIG_MISSING
    ]
    assert len(config_missing_events) == 1, [event.code for event in result.events]
    assert len(result.providers_skipped) == 2


# ---------------------------------------------------------------------------
# F-CFG-15 (symmetric with apply_lock): symlinked openclaw.json refused
# ---------------------------------------------------------------------------


def test_apply_unlock_refuses_symlinked_openclaw_json(
    openclaw_present: dict[str, Path],
) -> None:
    """F-CFG-15 symmetry: a symlinked openclaw.json must be refused with a
    SYMLINK_REFUSED event (not the generic CONFIG_UNREADABLE that
    unset_provider's flock-protected check would raise). Without the
    upfront short-circuit in apply_unlock, an attacker who plants
    ``~/.openclaw/openclaw.json -> ~/.bashrc`` between ``lock`` and
    ``unlock`` would see a misleading event tag in ``--json`` output.
    """
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    config_path = openclaw_present["config_path"]
    sentinel = openclaw_present["home"] / "sentinel.txt"
    sentinel.write_bytes(b"USER FILE - MUST SURVIVE\n")
    sentinel_before = sentinel.read_bytes()

    # Replace the regular file with a symlink pointing at the sentinel.
    config_path.unlink()
    config_path.symlink_to(sentinel)

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    codes = [event.code for event in result.events]
    assert OpenclawErrorCode.SYMLINK_REFUSED in codes, codes
    assert ("worthless-openai", "symlink_refused") in result.providers_skipped
    # Sentinel content untouched — the symlink target was not followed.
    assert sentinel.read_bytes() == sentinel_before
    # detected is True (host had OpenClaw); skill_installed stays False.
    assert result.detected is True
    assert result.skill_installed is False
