"""Phase 2.c — ``integration.apply_unlock()`` unit + functional tests.

Spec: ``engineering/research/openclaw-WOR-431-phase-2-spec.md`` §"Phase 2.c —
``unlock`` integration", §"Failure modes" rows RT-01/02/03 + F-XS-40/41,
§"Locked decisions" L1, L2, L3.

``apply_unlock`` is the symmetric undo of Phase 2.b's ``apply_lock``. It
runs from ``worthless unlock`` after the ``.env``/DB are restored. Per
L1/L2: failures here NEVER cause unlock-core to fail.

Each test docstring opens with ``"<F-ID/scope>: <description>"`` so the
coverage matrix can be regenerated by grep.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def fake_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Pin HOME at a tmp_path-rooted directory so detect() probes the sandbox.

    Mirrors the ``fake_home`` fixture in ``test_integration_apply_lock.py`` —
    ``apply_unlock`` calls ``detect()`` first, so HOME must be sandboxed.
    """
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("USERPROFILE", str(home))
    # Avoid project-local ``./openclaw.json`` discovery from pytest's cwd.
    monkeypatch.chdir(home)
    return home


@pytest.fixture
def openclaw_present(fake_home: Path) -> dict[str, Path]:
    """Pre-stage ``~/.openclaw/`` with a workspace and a minimal openclaw.json."""
    openclaw_dir = fake_home / ".openclaw"
    workspace = openclaw_dir / "workspace"
    workspace.mkdir(parents=True)
    config_path = openclaw_dir / "openclaw.json"
    config_path.write_text(
        json.dumps({"models": {"providers": {}}}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {"home": fake_home, "workspace": workspace, "config_path": config_path}


def _seed_provider(config_path: Path, name: str, base_url: str, api_key: str = "shard-a") -> None:
    """Helper: write a single provider entry into openclaw.json."""
    data = json.loads(config_path.read_text(encoding="utf-8"))
    data.setdefault("models", {}).setdefault("providers", {})[name] = {
        "baseUrl": base_url,
        "apiKey": api_key,
    }
    config_path.write_text(
        json.dumps(data, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Public API surface — sanity
# ---------------------------------------------------------------------------


def test_apply_unlock_is_exported() -> None:
    """Phase 2.c spec: ``integration.apply_unlock`` must be importable as the
    public symmetric-undo Stage-3 entry point.
    """
    from worthless.openclaw import integration

    assert hasattr(integration, "apply_unlock"), "apply_unlock missing"


# ---------------------------------------------------------------------------
# Detection short-circuit — no OpenClaw on host
# ---------------------------------------------------------------------------


def test_apply_unlock_no_openclaw_returns_early(fake_home: Path) -> None:
    """L1/L2 + Phase 2.c: host without OpenClaw → result with detected=False,
    no I/O, no exceptions. Symmetric with apply_lock's early exit.
    """
    from worthless.openclaw import integration

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    assert result.detected is False
    assert result.providers_set == ()
    assert result.skill_installed is False
    assert result.events == ()
    # No accidental file creation.
    assert not (fake_home / ".openclaw").exists()


# ---------------------------------------------------------------------------
# Provider removal
# ---------------------------------------------------------------------------


def test_apply_unlock_removes_provider_entry(openclaw_present: dict[str, Path]) -> None:
    """Phase 2.c: pre-stage ``worthless-openai`` in openclaw.json → after
    apply_unlock, that entry is gone (symmetric undo of Phase 2.b set_provider).
    """
    from worthless.openclaw import integration

    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]
    assert "worthless-openai" not in providers, providers
    assert result.detected is True


def test_apply_unlock_skips_non_worthless_entries(openclaw_present: dict[str, Path]) -> None:
    """L3 + Phase 2.c: pre-stage non-worthless ``openai`` entry → after
    apply_unlock, that entry is preserved. We only own ``worthless-*``.
    """
    from worthless.openclaw import integration

    _seed_provider(
        openclaw_present["config_path"],
        "openai",
        "https://api.openai.com",
        api_key="real-user-key",
    )
    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]
    assert "openai" in providers, "user's manual entry must survive"
    assert providers["openai"]["apiKey"] == "real-user-key"
    assert "worthless-openai" not in providers


# ---------------------------------------------------------------------------
# Skill folder removal
# ---------------------------------------------------------------------------


def test_apply_unlock_removes_skill_folder(openclaw_present: dict[str, Path]) -> None:
    """Phase 2.c + L3: pre-stage skill folder under workspace → after
    apply_unlock, folder is gone (symmetric undo of skill.install).
    """
    from worthless.openclaw import integration

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("placeholder\n", encoding="utf-8")

    integration.apply_unlock(aliases=[])

    assert not skill_dir.exists()


def test_apply_unlock_with_remove_skill_false_keeps_skill(
    openclaw_present: dict[str, Path],
) -> None:
    """Phase 2.c: ``remove_skill=False`` → provider entries are removed but
    skill folder is preserved. Lets future doctor --fix tear down only one
    half independently if desired.
    """
    from worthless.openclaw import integration

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("placeholder\n", encoding="utf-8")
    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    integration.apply_unlock(
        aliases=[("openai", "openai-deadbeef")],
        remove_skill=False,
    )

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    assert "worthless-openai" not in data["models"]["providers"]
    assert skill_dir.exists(), "skill folder must survive remove_skill=False"
    assert (skill_dir / "SKILL.md").exists()


# ---------------------------------------------------------------------------
# Idempotency — running twice on the same input is a no-op the second time
# ---------------------------------------------------------------------------


def test_apply_unlock_idempotent(openclaw_present: dict[str, Path]) -> None:
    """IDEM (Phase 2.c): apply_unlock twice on the same input → second call
    is a no-op (no errors, no provider removed because it's already gone).
    """
    from worthless.openclaw import integration

    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    first = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])
    second = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    # Both calls succeed; second has no error events.
    error_events = [e for e in second.events if e.level == "error"]
    assert error_events == [], error_events
    # And both report detected=True (OpenClaw is still on the host).
    assert first.detected is True
    assert second.detected is True


# ---------------------------------------------------------------------------
# Partial-failure paths (L1: NEVER raise into unlock-core)
# ---------------------------------------------------------------------------


def test_apply_unlock_partial_failure_returns_result(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-40 analogue: monkeypatch unset_provider to raise OSError
    → result reflects partial failure with a structured event, no raise.
    """
    from worthless.openclaw import config as config_mod
    from worthless.openclaw import integration

    def _exploding_unset(*_: object, **__: object) -> None:
        raise OSError("simulated EACCES on openclaw.json")

    monkeypatch.setattr(config_mod, "unset_provider", _exploding_unset)

    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    # Must not raise.
    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    assert result.detected is True
    error_events = [e for e in result.events if e.level == "error"]
    assert error_events, "OSError must surface as a structured event, not a raise"


def test_apply_unlock_partial_failure_config_unreadable(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-40 (CONFIG_UNREADABLE branch): monkeypatch unset_provider
    to raise OpenclawConfigError → result has CONFIG_UNREADABLE event,
    skipped provider list populated, no raise into unlock-core.
    """
    from worthless.openclaw import config as config_mod
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    def _raise_cfg(*_: object, **__: object) -> None:
        raise config_mod.OpenclawConfigError("simulated malformed JSON")

    monkeypatch.setattr(config_mod, "unset_provider", _raise_cfg)

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    codes = [e.code for e in result.events]
    assert OpenclawErrorCode.CONFIG_UNREADABLE in codes, codes
    assert ("worthless-openai", "config_unreadable") in result.providers_skipped


def test_apply_unlock_skill_uninstall_oserror_returns_result(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-41 (OSError branch): skill.uninstall raises a raw OSError
    (not OpenclawIntegrationError) → apply_unlock surfaces it as a
    SKILL_INSTALL_FAILED event without re-raising.
    """
    from worthless.openclaw import integration
    from worthless.openclaw import skill as skill_mod
    from worthless.openclaw.errors import OpenclawErrorCode

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)

    def _raise_oserror(*_: object, **__: object) -> None:
        raise OSError("simulated EACCES on rmtree")

    monkeypatch.setattr(skill_mod, "uninstall", _raise_oserror)

    result = integration.apply_unlock(aliases=[])

    codes = [e.code for e in result.events]
    assert OpenclawErrorCode.SKILL_INSTALL_FAILED in codes, codes


def test_apply_unlock_skill_uninstall_failure_returns_result(
    openclaw_present: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """L1 + F-XS-41 analogue: skill.uninstall raises → apply_unlock
    surfaces it as a structured event, never re-raises. Provider entry
    cleanup must still complete.
    """
    from worthless.openclaw import integration
    from worthless.openclaw import skill as skill_mod
    from worthless.openclaw.errors import (
        OpenclawErrorCode,
        OpenclawIntegrationError,
    )

    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text("placeholder\n", encoding="utf-8")
    _seed_provider(
        openclaw_present["config_path"],
        "worthless-openai",
        "http://127.0.0.1:8787/openai-deadbeef/v1",
    )

    def _exploding_uninstall(*_: object, **__: object) -> None:
        raise OpenclawIntegrationError(
            OpenclawErrorCode.SKILL_INSTALL_FAILED,
            "simulated uninstall failure",
        )

    monkeypatch.setattr(skill_mod, "uninstall", _exploding_uninstall)

    result = integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    error_events = [e for e in result.events if e.level == "error"]
    assert error_events, "skill failure must surface as a structured event"
    # Provider half still completed.
    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    assert "worthless-openai" not in data["models"]["providers"]


# ---------------------------------------------------------------------------
# RT-01: round-trip apply_lock → apply_unlock = byte-identical pre-lock state
# ---------------------------------------------------------------------------


def test_apply_lock_then_apply_unlock_round_trip_byte_identical(
    openclaw_present: dict[str, Path],
) -> None:
    """RT-01 (Phase 2.c spec): apply_lock followed by apply_unlock leaves
    openclaw.json byte-identical to its pre-apply_lock state. Phase 1's
    sort_keys=True atomic write makes byte-comparison deterministic.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    pre_bytes = config_path.read_bytes()

    integration.apply_lock(planned_updates=[("openai", "openai-deadbeef", "shard-a-token")])
    # Sanity: lock did write the entry.
    mid = json.loads(config_path.read_text(encoding="utf-8"))
    assert "worthless-openai" in mid["models"]["providers"]

    integration.apply_unlock(aliases=[("openai", "openai-deadbeef")])

    post_bytes = config_path.read_bytes()
    assert post_bytes == pre_bytes, (
        "RT-01 violated: openclaw.json differs after lock→unlock round-trip"
    )
    # And the skill folder we installed during apply_lock got swept too.
    assert not (openclaw_present["workspace"] / "skills" / "worthless").exists()
