"""Phase 2.b — ``integration.apply_lock()`` unit + functional tests.

Spec: ``engineering/research/openclaw-WOR-431-phase-2-spec.md`` §"Phase 2.b"
and §"Failure modes" rows F-CFG-13/15/16/23, F-XS-40/41/43, IDEM-24.

``apply_lock`` is the Stage-3 "magic" hook: after ``.env`` and DB are
committed (lock-core success), we attempt to wire OpenClaw. Per L1/L2,
failures here NEVER roll back lock-core — they surface as structured
events on the returned :class:`OpenclawApplyResult`.

Each test docstring opens with ``"<F-ID>: <description>"`` so the
coverage matrix can be regenerated by grep.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def fake_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Pin HOME at a tmp_path-rooted directory so detect() probes the sandbox.

    Mirrors the ``fake_home`` fixture in ``test_integration_detect.py`` —
    ``apply_lock`` calls ``detect()`` first, so HOME must be sandboxed.
    """
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("USERPROFILE", str(home))
    return home


@pytest.fixture
def openclaw_present(fake_home: Path) -> dict[str, Path]:
    """Pre-stage ``~/.openclaw/`` with a workspace and a minimal openclaw.json.

    Returns a dict with ``home``, ``workspace``, ``config_path`` for tests
    that need to assert on the on-disk artifacts.
    """
    openclaw_dir = fake_home / ".openclaw"
    workspace = openclaw_dir / "workspace"
    workspace.mkdir(parents=True)
    config_path = openclaw_dir / "openclaw.json"
    config_path.write_text(
        json.dumps({"models": {"providers": {}}}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {"home": fake_home, "workspace": workspace, "config_path": config_path}


# ---------------------------------------------------------------------------
# Public API surface — sanity
# ---------------------------------------------------------------------------


def test_apply_lock_is_exported() -> None:
    """Phase 2.b spec: ``integration.apply_lock`` and ``OpenclawApplyResult``
    must be importable as the public Stage-3 entry points.
    """
    from worthless.openclaw import integration

    assert hasattr(integration, "apply_lock"), "apply_lock missing"
    assert hasattr(integration, "OpenclawApplyResult"), "OpenclawApplyResult missing"


# ---------------------------------------------------------------------------
# Detection short-circuit
# ---------------------------------------------------------------------------


def test_apply_lock_no_openclaw_returns_early(
    fake_home: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """no-OpenClaw: detect()=absent → returns detected=False with no I/O.

    AC1 enforcement at the apply_lock layer: a host without OpenClaw must
    produce zero side effects from this call. providers_set/skipped empty,
    skill_installed=False, no events of any kind.
    """
    from worthless.openclaw import integration

    # Be sure: cwd has no project-local openclaw.json either.
    monkeypatch.chdir(tmp_path)

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-abc12345", "sk-shard-a-fake")],
    )

    assert result.detected is False
    assert result.config_path is None
    assert result.workspace_path is None
    assert result.skill_path is None
    assert result.providers_set == ()
    assert result.providers_skipped == ()
    assert result.skill_installed is False
    assert result.events == ()
    # No openclaw.json created on disk anywhere we can see.
    assert not (fake_home / ".openclaw" / "openclaw.json").exists()


# ---------------------------------------------------------------------------
# Config-stage failures
# ---------------------------------------------------------------------------


def test_apply_lock_skips_provider_with_conflicting_baseurl(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-CFG-13: pre-existing ``worthless-openai`` with a non-worthless
    baseUrl is a conflict — skip that provider, emit PROVIDER_CONFLICT,
    continue with others. Lock-core must remain unaffected.
    """
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    # Pre-poison: an existing worthless-openai entry pointing at the user's
    # own gateway (not our proxy) — looks like manual tweaking we mustn't
    # silently trample.
    config_path = openclaw_present["config_path"]
    config_path.write_text(
        json.dumps(
            {
                "models": {
                    "providers": {
                        "worthless-openai": {
                            "baseUrl": "https://my-own-gateway.example.com/v1",
                            "apiKey": "user-secret",
                        }
                    }
                }
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(openclaw_present["home"])  # avoid project-local pickup

    result = integration.apply_lock(
        planned_updates=[
            ("openai", "openai-aaaa1111", "sk-shard-a-openai"),
            ("anthropic", "anthropic-bbbb2222", "sk-shard-a-anthropic"),
        ],
    )

    # Detected, but worthless-openai skipped on conflict.
    assert result.detected is True
    assert "worthless-openai" not in result.providers_set
    assert any(name == "worthless-openai" for name, _ in result.providers_skipped)
    assert any(e.code == OpenclawErrorCode.PROVIDER_CONFLICT for e in result.events), [
        e.code for e in result.events
    ]
    # Anthropic still got written.
    assert "worthless-anthropic" in result.providers_set


def test_apply_lock_refuses_symlink_config(
    openclaw_present: dict[str, Path], tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-CFG-15: openclaw.json is a symlink → set_provider refuses + we
    emit a structured event. Must NOT raise; lock-core success unaffected.

    Phase 1's set_provider handles symlink refusal via _file_lock failure
    or atomic-write semantics. apply_lock catches OpenclawConfigError
    and emits SYMLINK_REFUSED / WRITE_FAILED / CONFIG_UNREADABLE per
    spec — the key contract is "no raise out".
    """
    from worthless.openclaw import integration

    # Replace the real config with a symlink pointing elsewhere.
    config_path = openclaw_present["config_path"]
    real_target = tmp_path / "outside-config.json"
    real_target.write_text(json.dumps({"models": {"providers": {}}}) + "\n", encoding="utf-8")
    config_path.unlink()
    config_path.symlink_to(real_target)
    monkeypatch.chdir(openclaw_present["home"])

    # Force set_provider to refuse symlinks via monkeypatch — Phase 1's
    # contract is "atomic + flock" and does follow symlinks today; the
    # safe-by-design contract for Phase 2.b is "we refuse them in apply_lock".
    from worthless.openclaw import config as config_mod
    from worthless.openclaw.config import OpenclawConfigError

    def _refusing_set_provider(*args: object, **kwargs: object) -> None:
        raise OpenclawConfigError("refusing to follow symlink")

    monkeypatch.setattr(config_mod, "set_provider", _refusing_set_provider)

    # Must not raise.
    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    assert result.detected is True
    # Provider wasn't written; event surfaced.
    assert "worthless-openai" not in result.providers_set
    assert len(result.events) >= 1


def test_apply_lock_warns_on_world_writable_config(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-CFG-16: world-writable openclaw.json → warn event, proceed.

    We don't chmod; we surface the risk and let the user decide. Still
    writes the provider (best-effort UX over paranoia, per spec row F16).
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    config_path.chmod(0o666)  # noqa: S103 — explicitly testing F-CFG-16 world-writable detection
    monkeypatch.chdir(openclaw_present["home"])

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    assert result.detected is True
    assert "worthless-openai" in result.providers_set
    # A warning event surfaced (at least one of CONFIG_UPDATED + a warning).
    assert any(e.level == "warn" for e in result.events), [(e.code, e.level) for e in result.events]


def test_apply_lock_warns_on_hardlinked_config(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-CFG-15 defense-in-depth: ``openclaw.json`` with ``st_nlink > 1``
    surfaces a WRITE_FAILED warning. Atomic-write semantically preserves
    the other hardlink (``os.replace`` rebinds the name to a new inode),
    so this is non-destructive — but the user almost certainly didn't
    mean to share inodes with their config, so we surface it for doctor
    to flag. No refusal; lock-core proceeds.

    Reference: security-auditor 2026-05-07 MEDIUM finding on commit 5bd33da.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    # Plant a hardlink to a sibling file in the same dir (cross-fs
    # hardlinks aren't possible; same-fs is enough to drive st_nlink).
    sibling = openclaw_present["home"] / ".openclaw" / "ghost.txt"
    config_path.write_text('{"models":{"providers":{}}}\n', encoding="utf-8")
    os.link(config_path, sibling)
    monkeypatch.chdir(openclaw_present["home"])

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    # Lock-core proceeded — provider was written.
    assert "worthless-openai" in result.providers_set
    # A warning event surfaced citing the hardlink count.
    hardlink_events = [
        e for e in result.events if e.level == "warn" and "hardlink" in e.detail.lower()
    ]
    assert hardlink_events, [(e.code, e.detail) for e in result.events]
    assert hardlink_events[0].extra is not None
    assert hardlink_events[0].extra.get("nlink") == "2"


def test_apply_lock_recreates_deleted_config(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-CFG-23: openclaw.json deleted between detect and write → set_provider
    recreates it. Final state has provider populated; no error raised.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    monkeypatch.chdir(openclaw_present["home"])

    # Delete after detect would normally have run — patch detect to return
    # the (now-vanished) config_path so apply_lock thinks it should write.
    real_detect = integration.detect

    def _detect_then_unlink() -> object:
        state = real_detect()
        # Side effect: the file disappears between detect() returning and
        # set_provider running. Simulates a daemon-kicked vanish.
        if config_path.exists():
            config_path.unlink()
        return state

    monkeypatch.setattr(integration, "detect", _detect_then_unlink)

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    assert result.detected is True
    # set_provider's atomic-write recreates the file.
    assert config_path.exists()
    assert "worthless-openai" in result.providers_set


# ---------------------------------------------------------------------------
# Cross-stage failure isolation (L1/L2)
# ---------------------------------------------------------------------------


def test_apply_lock_swallows_config_write_failure(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-XS-40: config write fails (OSError) → emit WRITE_FAILED, return
    result with empty providers_set, DO NOT RAISE.

    The lock-core success contract (.env + DB) is owned by the caller;
    this test only verifies apply_lock's contract: failures here surface
    structurally, never as exceptions.
    """
    from worthless.openclaw import config as config_mod
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    monkeypatch.chdir(openclaw_present["home"])

    def _exploding_set_provider(*args: object, **kwargs: object) -> None:
        raise OSError("simulated EACCES")

    monkeypatch.setattr(config_mod, "set_provider", _exploding_set_provider)

    # Critical: must not raise.
    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    assert result.detected is True
    assert "worthless-openai" not in result.providers_set
    assert any(e.code == OpenclawErrorCode.WRITE_FAILED for e in result.events), [
        e.code for e in result.events
    ]


def test_apply_lock_swallows_skill_install_failure(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-XS-41: config write OK, skill install raises → emit
    SKILL_INSTALL_FAILED, providers_set populated, skill_installed=False,
    DO NOT RAISE.
    """
    from worthless.openclaw import integration, skill
    from worthless.openclaw.errors import (
        OpenclawErrorCode,
        OpenclawIntegrationError,
    )

    monkeypatch.chdir(openclaw_present["home"])

    def _exploding_install(*args: object, **kwargs: object) -> None:
        raise OpenclawIntegrationError(
            OpenclawErrorCode.SKILL_INSTALL_FAILED, "simulated rmtree fail"
        )

    monkeypatch.setattr(skill, "install", _exploding_install)

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    assert result.detected is True
    assert "worthless-openai" in result.providers_set, "config write should still succeed"
    assert result.skill_installed is False
    assert any(e.code == OpenclawErrorCode.SKILL_INSTALL_FAILED for e in result.events)


def test_apply_lock_emits_config_updated_event_on_success(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-XS-43: successful config write → emit CONFIG_UPDATED with the
    new config_path so doctor + --json consumers can confirm the daemon
    reload point.
    """
    from worthless.openclaw import integration
    from worthless.openclaw.errors import OpenclawErrorCode

    monkeypatch.chdir(openclaw_present["home"])

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-a")],
    )

    assert result.detected is True
    assert "worthless-openai" in result.providers_set
    updated_events = [e for e in result.events if e.code == OpenclawErrorCode.CONFIG_UPDATED]
    assert len(updated_events) >= 1, [e.code for e in result.events]


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------


def test_apply_lock_is_idempotent(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """IDEM-24: calling apply_lock twice with the same input produces
    identical state — no duplicate providers, no errors.

    Second call is a no-op-shaped success: provider already set to the
    same value, skill folder already populated.
    """
    from worthless.openclaw import integration

    monkeypatch.chdir(openclaw_present["home"])

    planned = [("openai", "openai-aaaa1111", "sk-shard-a")]

    first = integration.apply_lock(planned_updates=planned)
    second = integration.apply_lock(planned_updates=planned)

    assert first.detected is True
    assert second.detected is True
    assert first.providers_set == second.providers_set == ("worthless-openai",)

    # Config file: provider entry must be present exactly once with
    # the same baseUrl after both calls.
    raw = openclaw_present["config_path"].read_text(encoding="utf-8")
    data = json.loads(raw)
    providers = data["models"]["providers"]
    assert list(providers.keys()).count("worthless-openai") == 1
    assert providers["worthless-openai"]["baseUrl"].endswith("/openai-aaaa1111/v1"), providers[
        "worthless-openai"
    ]


# ---------------------------------------------------------------------------
# Happy path
# ---------------------------------------------------------------------------


def test_apply_lock_happy_path_writes_providers_and_installs_skill(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Happy path: workspace exists + valid config + 2 aliases → both
    ``worthless-openai`` and ``worthless-anthropic`` get written, skill
    folder appears under workspace/skills/worthless/, events log shows
    the success sequence.
    """
    from worthless.openclaw import integration

    monkeypatch.chdir(openclaw_present["home"])

    result = integration.apply_lock(
        planned_updates=[
            ("openai", "openai-aaaa1111", "sk-shard-a-openai"),
            ("anthropic", "anthropic-bbbb2222", "sk-shard-a-anthropic"),
        ],
    )

    assert result.detected is True
    assert set(result.providers_set) == {"worthless-openai", "worthless-anthropic"}
    assert result.skill_installed is True

    # Config file mutated correctly.
    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]
    assert providers["worthless-openai"]["baseUrl"].endswith("/openai-aaaa1111/v1")
    assert providers["worthless-openai"]["apiKey"] == "sk-shard-a-openai"
    assert providers["worthless-anthropic"]["baseUrl"].endswith("/anthropic-bbbb2222/v1")
    assert providers["worthless-anthropic"]["apiKey"] == "sk-shard-a-anthropic"

    # Skill installed under workspace/skills/worthless/.
    skill_dir = openclaw_present["workspace"] / "skills" / "worthless"
    assert skill_dir.exists()
    assert (skill_dir / "SKILL.md").exists()


def test_apply_lock_uses_custom_proxy_base_url(
    openclaw_present: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Custom proxy_base_url: callers (and tests) can override the proxy
    host so the integration is portable across non-default ports.
    """
    from worthless.openclaw import integration

    monkeypatch.chdir(openclaw_present["home"])

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-cccc3333", "sk-shard")],
        proxy_base_url="http://custom.host:9999",
    )

    assert result.detected is True
    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]
    assert providers["worthless-openai"]["baseUrl"] == "http://custom.host:9999/openai-cccc3333/v1"


# ---------------------------------------------------------------------------
# Regressions surfaced by live verification (WOR-431 evidence + simplify pass)
# ---------------------------------------------------------------------------


def test_apply_lock_writes_models_array_and_api_field(openclaw_present: dict[str, Path]) -> None:
    """Regression — daemon REJECTED config without ``models: []`` array.

    Live test against ghcr.io/openclaw/openclaw:latest reported:
    ``models.providers.worthless-openai.models: Invalid input: expected
    array, received undefined``. Without this the skill never registered
    in the real flow despite unit tests passing. Both ``models`` and
    ``api`` must be on every provider entry we write.
    """
    from worthless.openclaw import integration

    result = integration.apply_lock(
        planned_updates=[
            ("openai", "openai-aaaa1111", "sk-shard-a"),
            ("anthropic", "anthropic-bbbb2222", "sk-shard-b"),
        ],
    )
    assert result.detected is True

    data = json.loads(openclaw_present["config_path"].read_text(encoding="utf-8"))
    providers = data["models"]["providers"]

    # AC: every entry has `models` array (empty is fine) so daemon accepts.
    assert providers["worthless-openai"]["models"] == []
    assert providers["worthless-anthropic"]["models"] == []
    # AC: `api` identifies the wire protocol per provider type.
    assert providers["worthless-openai"]["api"] == "openai-completions"
    assert providers["worthless-anthropic"]["api"] == "anthropic-messages"


def test_apply_lock_preserves_existing_models_array(openclaw_present: dict[str, Path]) -> None:
    """If the user (or a prior install) put real models in the entry, keep them.

    We only fill ``models: []`` as a default for NEW entries. An existing
    array (e.g., a curated list of GPT-4 / Claude variants the user
    chose) survives a re-run of ``worthless lock``.
    """
    from worthless.openclaw import integration

    config_path = openclaw_present["config_path"]
    config_path.write_text(
        json.dumps(
            {
                "models": {
                    "providers": {
                        "worthless-openai": {
                            "baseUrl": "http://127.0.0.1:8787/openai-aaaa1111/v1",
                            "apiKey": "sk-shard-old",
                            "api": "openai-completions",
                            "models": [{"id": "gpt-4o", "name": "GPT-4o"}],
                        }
                    }
                }
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard-new")],
    )

    data = json.loads(config_path.read_text(encoding="utf-8"))
    entry = data["models"]["providers"]["worthless-openai"]
    assert entry["models"] == [{"id": "gpt-4o", "name": "GPT-4o"}], "existing models clobbered"
    assert entry["apiKey"] == "sk-shard-new", "apiKey not refreshed"


def test_apply_lock_refuses_symlinked_openclaw_json(openclaw_present: dict[str, Path]) -> None:
    """F-CFG-15 production gap — set_provider must refuse symlinks.

    Security: an attacker plants ~/.openclaw/openclaw.json as a symlink
    to ~/.bashrc. Without the symlink check, ``os.replace`` clobbers
    the link target, destroying the user's shell config. The test
    monkeypatched set_provider before; this test exercises the REAL
    production path (Phase 1 ``_refuse_if_symlink`` inside the flock).
    """
    from worthless.openclaw import integration

    # Replace openclaw.json with a symlink to a sibling file we don't want clobbered.
    config_path = openclaw_present["config_path"]
    target = openclaw_present["home"] / "innocent-bystander.txt"
    target.write_text("DO NOT TOUCH ME\n", encoding="utf-8")
    config_path.unlink()
    config_path.symlink_to(target)

    result = integration.apply_lock(
        planned_updates=[("openai", "openai-aaaa1111", "sk-shard")],
    )

    # Lock-core never raises (L1). The integration result records the refusal.
    assert any(
        "F-CFG-15" in event.detail or "symlink" in event.detail.lower() for event in result.events
    ), f"expected a symlink-refusal event, got: {[e.detail for e in result.events]}"
    # The link target MUST be untouched (the actual security property).
    assert target.read_text(encoding="utf-8") == "DO NOT TOUCH ME\n", "symlink target was clobbered"
